# Generated by Django 3.1.7 on 2021-07-08 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_auto_20210624_0815'),
        ('brc_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField()),
                ('incoming1_qty', models.IntegerField()),
                ('incoming2_qty', models.IntegerField()),
                ('finished_qty', models.IntegerField()),
                ('liner', models.CharField(max_length=55)),
                ('tubs', models.CharField(max_length=55)),
                ('lids', models.CharField(max_length=55)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shinished_product', to='brc_app.finished')),
                ('incoming1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_product1', to='brc_app.incoming')),
                ('incoming2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_product2', to='brc_app.incoming')),
                ('released_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='login_app.user')),
            ],
        ),
    ]
