# Generated by Django 3.1.7 on 2021-07-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
