# Generated by Django 3.1.7 on 2021-07-19 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brc_app', '0002_auto_20210718_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receive',
            old_name='by_employee',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='ship',
            old_name='by_employee',
            new_name='employee',
        ),
    ]
