# Generated by Django 3.1.7 on 2021-07-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brc_app', '0002_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='employee',
            field=models.ManyToManyField(related_name='production_by', to='brc_app.Employee'),
        ),
    ]
