# Generated by Django 3.1.7 on 2021-07-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brc_app', '0002_employee_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
