# Generated by Django 3.1.7 on 2021-07-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brc_app', '0003_production_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finished',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='incoming',
            name='qty',
        ),
        migrations.AddField(
            model_name='receive',
            name='qty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ship',
            name='qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
