# Generated by Django 3.1.7 on 2021-07-06 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brc_app', '0004_customer_supplier_trucking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='street',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='street',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='trucking',
            old_name='street',
            new_name='address',
        ),
    ]
