# Generated by Django 3.1.7 on 2021-07-28 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brc_app', '0004_auto_20210728_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_produceds', to='brc_app.product'),
        ),
        migrations.AlterField(
            model_name='prodproduct',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produced', to='brc_app.production'),
        ),
    ]
