# Generated by Django 3.1.7 on 2021-07-06 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brc_app', '0005_auto_20210705_1715'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trucking',
            new_name='Truck',
        ),
    ]
