# Generated by Django 3.1.7 on 2021-06-24 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_level',
            new_name='level',
        ),
    ]
